default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["DB_USERNAME"] || 'postgres' %> 
  password: <%= ENV["DB_PASSWORD"] || 'password' %> 

development:
  <<: *default
  database: user_goals_development
  host: localhost
  
production:
  <<: *default
  database: user_goals_production
  
test:
  <<: *default
  database: user_goals_test
  host: localhost
